name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  hardhat:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npx hardhat compile
      - run: npm run test:smoke
      - run: npm run test:unit
      - run: npm run test:integration
      - run: npm run test:upgradeability
